### PR TITLE
Treating shuttle routes as 'unpreferred'

### PR DESCRIPTION
**Pull request by lboyarsky**
Ticket: [mark shuttle routes as less preferred in OTP](https://app.asana.com/0/810933294009540/1137714962718721/f)

This seems to be working as intended and I've checked under debugger that it's actually being executed; the problem, however, is that I cannot find any trip plans where this change would make a difference.. Do we have any shuttles, which could be easily avoided by using other routes? I haven't found any such examples.

### CODE REVIEW

**Comment by paulswartz** [comment]
https://www.mbta.com/trip-planner?_utf8=%E2%9C%93&plan%5Bfrom%5D=Kenmore&plan%5Bfrom_latitude%5D=42.348949&plan%5Bfrom_longitude%5D=-71.095169&plan%5Bto%5D=Boylston+St+%40+Hammond+St&plan%5Bto_latitude%5D=42.323275&plan%5Bto_longitude%5D=-71.163979&plan%5Btime%5D=depart&plan%5Bdate_time%5D%5Bhour%5D=10&plan%5Bdate_time%5D%5Bminute%5D=30&plan%5Bdate_time%5D%5Bam_pm%5D=PM&plan%5Bdate_time%5D%5Bmonth%5D=9&plan%5Bdate_time%5D%5Bday%5D=4&plan%5Bdate_time%5D%5Byear%5D=2019&plan%5Bmodes%5D%5Bsubway%5D=false&plan%5Bmodes%5D%5Bsubway%5D=true&plan%5Bmodes%5D%5Bcommuter_rail%5D=false&plan%5Bmodes%5D%5Bcommuter_rail%5D=true&plan%5Bmodes%5D%5Bbus%5D=false&plan%5Bmodes%5D%5Bbus%5D=true&plan%5Bmodes%5D%5Bferry%5D=false&plan%5Bmodes%5D%5Bferry%5D=true&plan%5Boptimize_for%5D=best_route#plan_result_focus

This prefers the Green-D shuttle to the 60. It also makes me think our shuttle timings might be too aggressive?

**Comment by lboyarsky** [comment]
This trip plan is the same with the new version as well.. looking into it.

**Comment by lboyarsky** [comment]
So I've ended up introducing separate penalty value for shuttles because "unpreferred" penalty value seems to be too low. Basically the value of 600, which I'm now using, means that a trip, which uses shuttles, will be less preferred than a trip without them even if the trip without them is up to 600 seconds longer than the trip with shuttles. 

Separate problem was that by default trip plans were sorted by start time, so no matter what was the penalty, the trips with shuttles ended up being the first even despite of being "less preferred" if shuttle leaves earlier, so I had to introduce the new way to compare plans as well. 

Before vs After:
image

But now all the tests (both unit and integration) are failing, looking into it.

**Comment by lboyarsky** [comment]
The single integration test, which is failing, shows minor difference in walking directions, which is probably due to updates in OSM:

image

So I'd say it's good to go.

**Pull request merged**
