### PR TITLE
chore: Use Trillium-hosted GTFS file for Massport

### PR DESCRIPTION
**Pull request by jfabi**
Our S3-hosted Massport GTFS file has had its `feed_info` expired, which is why Massport buses are currently excluded from MBTA.com Trip Planner results.

We could manually update the `feed_info.txt` file (the `service_id`s were already set to go through September 2023, so no update needed there) and reupload the resulting file to S3, but it also looks like Massport now has a stable URL for their GTFS-static data (hosted by Trillium, which produces their data).

So instead of updating this likely outdated S3-based file, we point OpenTripPlanner to instead download the newest public-facing GTFS from Massport's source itself.

This branch is being deployed to `dev-green` so that we can verify that it works in that environment, and so we can check that the schedule in the current file version makes relative sense (it hasn't always, which is part of the reason we at some point moved to using an MBTA-hosted file).

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203331820183719

### CODE REVIEW

**Comment by jfabi** [comment]
@thecristen @bklebe I put together this branch to download Massport's updated GTFS, so that it begins showing up again in Trip Planner. Unfortunately, I'm coming across two issues in CI and upon deploying to `dev-green`, and I'm not entirely sure whether or not they're related:
- I'm getting some sort of CI error ([see build logs](https://github.com/mbta/OpenTripPlanner/actions/runs/3970662059/jobs/6806647663)). From my inexperienced read, it seems to be about a unit test, which seems unexpected. I'm hoping it's not some sort of dependency issue—is there a way we can run the CI tests on the main branch (I couldn't immediately figure it out)?
- Any `dev-green` Trip Planner result involving Massport shuttles (both the on-airport and the Logan Express routes) comes up with a 500 error: The page doesn't even load. When I build OTP locally and grab the external Massport GTFS file, I'm successfully able to get results involving the Logan Express bus routes, so from the back-end, it seems like _something_ is working. Not sure if it's related to the issues previously addressed in https://github.com/mbta/dotcom/pull/1105 ...maybe it's worth seeing if we could debug an example on dotcom where this is failing?

Screen Shot 2023-01-20 at 14 28 14
Screen Shot 2023-01-20 at 14 21 42

**Comment by thecristen** [comment]
I'm gonna rerun those OTP tests in case it was a fluke. But anyway, oof, I'll add a ticket to our backlog to investigate this with local OTP and Dotcom builds on our end.

**Comment by thecristen** [comment]
Welp, it looks like those tests _are_ failing on the master branch, so it's not related to this GFTS change.
Still looking into the Dotcom failure though.

**Comment by thecristen** [comment]
@jfabi I just updated Dotcom's dev-green with what I hope to be the fix. 🙏🏼 Can you please give it another try and let me know what you get? Thanks!

**Comment by jfabi** [comment]
> @jfabi I just updated Dotcom's dev-green with what I hope to be the fix. 🙏🏼 Can you please give it another try and let me know what you get? Thanks!

🎉 I'm able to make plans for both types of Massport buses (on-airport shuttles and Logan Express), thanks!

_Side note:_ I'm noticing that trip plans involving Logan Express don't have their fares incorporated (they're not free 😢) in the calculator, though that would be something for a follow-up ticket, I'm assuming:

Screen Shot 2023-01-23 at 13 22 38

**Comment by thecristen** [comment]
Great! I'm going to go ahead and merge the fix into our master branch and deploy it today.
@jfabi Yep, can you please send us an Asana ticket about the Logan Express fare issue? Thank you! :) 

Sadly I'm not sure I am able to tackle the CI failing tests issue, as I never got around to being able to even build OTP locally on this laptop yet, which prohibits effective debugging. I'm happy to merge this in anyway as we've clearly built it and tried it out in various ways by now. 🤪

**Comment by jfabi** [comment]
> Sadly I'm not sure I am able to tackle the CI failing tests issue, as I never got around to being able to even build OTP locally on this laptop yet, which prohibits effective debugging. I'm happy to merge this in anyway as we've clearly built it and tried it out in various ways by now. 🤪

@thecristen I took a small dive into this yesterday and discovered where this issue originated—it was actually due to my work on https://github.com/mbta/onebusaway-gtfs-modules/pull/9. This stripped out OpenTripPlanner's (v1) outdated handling of  _areas.txt_. That seemed to work fine, except we never checked that _**OpenTripPlanner's**_ test suite still worked fine...as it turns out, it did not.

There is a sample GTFS file and test suite (called "VermontFlexRoutingTest") that uses some of that functionality, which I purposely broke that in that previous PR. The last two commits here in this PR adjust the sample file and tests accordingly.

**Comment by bklebe** [comment]
Anything I need to review here? Looks like @thecristen has got it nailed down.

**Review by thecristen — APPROVED** [review]
🤩 Thanks for the teamwork!

**Pull request merged**
