### PR TITLE
Update to latest dev OTP version + continuous boarding support

### PR DESCRIPTION
**Pull request by lboyarsky**
Ticket: [Update TripPlanner to accept new continuous boarding values](https://app.asana.com/0/810933294009540/1120226289639214/f)

Ran [integration tests](https://github.com/mbta/otp-deploy/pull/17) and found out the following:
- new version fixes `distance` values (length of given itinerary leg) but it doesn't seem that dotcom uses those. 
- new version adds few more output parameters (e.g. `flexDrtAdvanceBookMin`) but it doesn't seem to affect anything; dotcom is able to ignore them;
- there were small difference in walking directions in Providence, which I think is due to OSM changes;
- there are minor differences in arrival / departure times (+/- few seconds); haven't thoroughly investigated those, but I believe it's not a big deal and somewhat expected with a major update. 

Otherwise the trip plans are the same between current production version and this version. **~However, it takes visibly more time to get responses (something like 2s vs 1s), not sure if this is ok for us. Performance seems to be back to normal when I disable `useFlexService` option.~ it's been fixed**

Continuous boarding example ([link](https://dev.mbtace.com/trip-planner?_utf8=%E2%9C%93&plan%5Bfrom%5D=Wellington&plan%5Bfrom_latitude%5D=42.40237&plan%5Bfrom_longitude%5D=-71.077082&plan%5Bto%5D=49+Cushing+Street%2C+Medford%2C+MA%2C+USA&plan%5Bto_latitude%5D=42.4142089&plan%5Bto_longitude%5D=-71.0968295&plan%5Btime%5D=depart&plan%5Bdate_time%5D%5Bhour%5D=7&plan%5Bdate_time%5D%5Bminute%5D=50&plan%5Bdate_time%5D%5Bam_pm%5D=AM&plan%5Bdate_time%5D%5Bmonth%5D=8&plan%5Bdate_time%5D%5Bday%5D=7&plan%5Bdate_time%5D%5Byear%5D=2019&plan%5Bmodes%5D%5Bsubway%5D=false&plan%5Bmodes%5D%5Bsubway%5D=true&plan%5Bmodes%5D%5Bcommuter_rail%5D=false&plan%5Bmodes%5D%5Bcommuter_rail%5D=true&plan%5Bmodes%5D%5Bbus%5D=false&plan%5Bmodes%5D%5Bbus%5D=true&plan%5Bmodes%5D%5Bferry%5D=false&plan%5Bmodes%5D%5Bferry%5D=true&plan%5Boptimize_for%5D=best_route#plan_result_focus)):
image
(note "corner of XXX" instead of GTFS stop).

### CODE REVIEW

**Comment by lboyarsky** [comment]
Nope, it is still slow if I switch it back to 400m. The only difference in this case is that we don't see any impact on our trip plans (which was the result of my initial investigation) because we normally have GTFS stops more close than that, but slowness is still there.

**Comment by lboyarsky** [comment]
After spending some time profiling, I narrowed the issue down to `flexUseReservationServices` flag, which is used for trips requiring the reservation. I believe we don't have such trips in GTFS at the moment, so disabling this option should not have any customer visible impact. I've also changed the string constants a bit to capitalize the labels ("corner" -> "Corner"):

image

Now everything works as fast as with the old version. I've also run the integration tests and all of them exepectedly fail (new version has new fields added to response json); however, when I filtered the new fields, they mostly passed. I've checked the remaning differences and they are minor (e.g. duration of the trip changes +/- 1 second), so I'd say it should be good to go.

**Comment by lboyarsky** [comment]
Hi @liana, please take a look at the picture above and let us know if you have any questions or concerns about this new feature. 

Another question raised by @jfabi is whether we want to continune showing intermediate stops (those "9 stops" on the screenshot) for such trip plans. In my point of view, it makes sense to keep them as they are **if** the stops are marked / announced but we don't know whether this is the case. Please let us know what's your point of view about it as it sounds more like a product question than a technical one. 

Thanks!

**Comment by lboyarsky** [comment]
Update: it looks like the stops are not marked indeed: https://www.google.com/maps/@42.4122068,-71.0954331,3a,26.3y,14.19h,89.88t/data=!3m6!1e1!3m4!1ss3tHqRxy6Xc56wHnBIL3Hw!2e0!7i16384!8i8192

**Comment by liana** [comment]
@lboyarsky Thanks for looping me in. At first blush, this looks like a better user experience. Let me know if you need anything from the website team.

**Comment by lboyarsky** [comment]
@liana glad that you like it! Can you address the second part of the question? That is, whether we should hide intermediate stops for such trips or not.

**Comment by liana** [comment]
@lboyarsky I agree that it seems to make sense to keep them. It's hard to know whether they are announced or actual stops but at the very least it seems helpful for the rider to track progress of the trip should they choose to expand the collapsed details. Honestly, it's hard to say for sure without seeing more examples but my inclination would be to keep them.

**Comment by lboyarsky** [comment]
@paulswartz nope. It is, however, configurable as a request parameter (similar to `walkReluctance`). But I thought that it's easier to change the default value here than to change dotcom code to pass additional parameters.

**Pull request merged**
