### PR TITLE
Update maven download URL

### PR DESCRIPTION
**Pull request by EmmaSimon**
The dlcdn URLs are unreliable and only host the latest version. The archive URL should be more stable.

### CODE REVIEW

**Comment by firestack** [comment]
Is there any way to test the docker build process to make sure that this works with the new maven version? If they follow semver, then this seems fine, but I don't know if any of the tests that run on PR before merge actually interact with the docker file?

**Comment by EmmaSimon** [comment]
@firestack I started running it locally right after I put this up, the install step that's failing in prod worked fine, then it errored out on some plugin validation step, downgrading to the version it was using before and trying again.

**Comment by EmmaSimon** [comment]
Ugh, running the docker build locally is painfully slow because it needs to do platform emulation because of the ARM chip, and it keeps hanging (unrelated to the change).

But it builds and deploys fine in the workflow:
https://github.com/mbta/OpenTripPlanner/actions/runs/5324848911/jobs/9644734504

**Review by firestack — APPROVED** [review]

**Comment by firestack** [comment]
Would maybe consider waiting for @jfabi to also look, but if the build/pipeline works than LGTM.

**Comment by jfabi** [comment]
> Would maybe consider waiting for @jfabi to also look, but if the build/pipeline works than LGTM.

Yeah, I think if it works, it works... 🙂 (But I did see the Winthrop Ferry working in `otp-dev-blue`, so 🎉!)

**Pull request merged**
